
### Criando usuário
POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "andre",
   "email": "andre@gmail.com",
   "password": "123456"
}


###  Login
# @name loginUser
POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "email": "andre@gmail.com",
   "password": "123456"
}

###
@token = {{ loginUser.response.body.access_token }} 

### Cadastro Colaborador
POST http://localhost:3000/api/collaborators
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Gustavo Lima"
   
}

### Cadastro Workshop
POST http://localhost:3000/api/workshops
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Falando sobre negócios",
   "dateCompletion": "01-08-2024",
   "description": "Tecnologias bussiness"
   
}

### Cadastro Ata de Presença
POST http://localhost:3000/api/attendance-sheets
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "workshopId": 3
}

### Adicionar colaborador na ata de presença de um workshop 
POST http://localhost:3000/api/attendance-sheet/collaborators
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "attendanceSheetId": 3,
   "collaboratorId": 5
}

### Remover colaborador da ata de presença 
DELETE http://localhost:3000/api/attendance-sheet/collaborators/1/collaborator/3
Content-Type: application/json
Authorization: Bearer {{token}}



### Lista de colaboradores
GET http://localhost:3000/api/collaborators
Content-Type: application/json
Authorization: Bearer {{token}}


### Lista de Atas
GET http://localhost:3000/api/attendance-sheets
Content-Type: application/json
Authorization: Bearer {{token}}


### Lista de workshops
GET http://localhost:3000/api/workshops
Content-Type: application/json
Authorization: Bearer {{token}}


### Lista de Colaboradores na ata
GET http://localhost:3000/api/attendance-sheet/collaborators
Content-Type: application/json
Authorization: Bearer {{token}}


### Filtro de workshop por colaborador
GET http://localhost:3000/api/attendance-sheets/workshop/collaborator?collaborator=Maria Lima de Sá
Content-Type: application/json
###Authorization: Bearer {{token}}

### Filtro de workshop por data do workshop
GET http://localhost:3000/api/attendance-sheets/workshop/date?date=01-08-2024
###Authorization: Bearer {{token}}

### Filtro de workshop por nome do workshop
GET http://localhost:3000/api/attendance-sheets/workshop/name?name=Desenvolvimento Web
Content-Type: application/json
###Authorization: Bearer {{token}}


### Filtro de workshop por nome do workshop
GET http://localhost:3000/api/attendance-sheets/collaborator/3
Content-Type: application/json
###Authorization: Bearer {{token}}