
### Criando usuário
POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "josenete",
   "email": "josenet@gmail.com",
   "password": "123456"
}




###  Login
# @name loginUser
POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "email": "josenet@gmail.com",
   "password": "123456"
}


###
@token = {{ loginUser.response.body.access_token }} 


GET http://localhost:3000/auth/me
Authorization: Bearer {{token}}

### Cadastro Colaborador
POST http://localhost:3000/api/collaborators
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Hélio Nunes da Silva"
   
}

### Cadastro Workshop
POST http://localhost:3000/api/workshops
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Saúde ambiental",
   "dateCompletion": "10-08-2024",
   "description": "Como preservar o meio ambiente"
   
}

### Cadastro Ata de Presença
POST http://localhost:3000/api/attendance-sheets
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "workshopId": 6
}

### Adicionar colaborador na ata de presença de um workshop 
POST http://localhost:3000/api/attendance-sheet/collaborators
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "attendanceSheetId": 6,
   "collaboratorId": 5
}

### Remover colaborador da ata de presença 
DELETE http://localhost:3000/api/attendance-sheet/collaborators/3/collaborator/1
Content-Type: application/json
Authorization: Bearer {{token}}



### Lista de colaboradores
GET http://localhost:3000/api/collaborators
Content-Type: application/json
Authorization: Bearer {{token}}



### Lista de workshops
GET http://localhost:3000/api/workshops
Content-Type: application/json
Authorization: Bearer {{token}}


### Lista de Colaboradores na ata
GET http://localhost:3000/api/attendance-sheet/collaborators
Content-Type: application/json
Authorization: Bearer {{token}}


### Filtro de workshop por colaborador
GET http://localhost:3000/api/attendance-sheets/workshop/collaborator?collaborator=Maria Lima de Sá
Content-Type: application/json
Authorization: Bearer {{token}}

### Filtro de workshop por data do workshop
GET http://localhost:3000/api/attendance-sheets/workshop/date?date=01-08-2024
Authorization: Bearer {{token}}

### Filtro de workshop por nome do workshop
GET http://localhost:3000/api/attendance-sheets/workshop/name?name=Desenvolvimento Web
Content-Type: application/json
Authorization: Bearer {{token}}


### Filtro de workshop por nome do workshop
GET http://localhost:3000/api/attendance-sheets/collaborator/4
Content-Type: application/json
Authorization: Bearer {{token}}